### ISSUE TITLE
UglifyJS incompatibility

### ISSUE THREAD

**Issue by lukas1994** [latentflip/deval#1]
This doesn't work with webpack's UglifyJS plugin. Since it doesn't understand those `$...$` variables. Any ideas how to make this work?

**Comment by lukas1994** [comment]
any updates on this?

**Comment by latentflip** [comment]
No current plans to fix this I’m afraid - I’m not sure it’s even possible to fix in this library.

You might want to look at the `mangle` options in uglify to disable variable name mangling, or to reserve the specific variable names you are using.
